### ISSUE TITLE
Design new navbar with MDBootstrap 5

### ISSUE THREAD

**Issue by MrTheBank** [kim-pukkanun/CN334-Team_63#3]

**Comment by kim-pukkanun** [comment]
We will use light theme on the front-end aight? Make it more work environment friendly

**Comment by MrTheBank** [comment]
> We will use light theme on the front-end aight? Make it more work environment friendly

Yes, Also I already update assets to MDBootstrap 5 white mode.
https://github.com/kim-pukkanun/CN334-Team_63/issues/2#issuecomment-1009954444

**Comment by MrTheBank** [comment]
https://github.com/kim-pukkanun/CN334-Team_63/commit/c5417e91a46967d2b28462b4b0f8f8e5fbe8943e
- Navbar with MDBootstrap 5
![image](https://user-images.githubusercontent.com/16158569/149287958-33864ce2-ea5f-408d-875c-638ec545beae.png)
