### ISSUE TITLE
Optional Feature : Progress bar defined how many current, expired, finish task with color in percent

### ISSUE THREAD

**Issue by kim-pukkanun** [kim-pukkanun/CN334-Team_63#5]

**Comment by MrTheBank** [comment]
Done. https://github.com/kim-pukkanun/CN334-Team_63/commit/3f3a4bceaa73e4c9d0c8508d2fcecaf6e36d637f
![image](https://user-images.githubusercontent.com/16158569/149614873-72acea36-6333-4bb2-85aa-0e7905cf90a2.png)
